# Maven


# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'complete/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'install dockerfile:build '



- task: Docker@2
  inputs:
    containerRegistry: 'steve-dillon1'
    command: 'login'

- task: CmdLine@2
  inputs:
    script: |
      docker tag springio/gs-spring-boot-docker:latest steve-dillon1/gs-spring-boot-docker:$(Build.BuildId)
      docker push steve-dillon1/gs-spring-boot-docker:$(build.BuildId)
