apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: helloworld-whatever
  #type: NodePort  
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9376
    nodePort: 30080